# -*- coding: utf-8 -*-
"""Covid Diagnosis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WOD8uzfcXLpNyn8nDcqVL3Ns3w2KKJmj
"""

#connect to google drive
from google.colab import drive
drive.mount('/content/drive')

regular = "/content/drive/My Drive/Colab Notebooks/Regular.jpg"
covid = "/content/drive/My Drive/Colab Notebooks/Covid.jpg"

print("WELCOME TO COVID DETECTION THROUGH IMAGES\n\nYou have to insert an image of XRay of your lungs")

from PIL import Image
import cv2
import numpy as np
import operator
#put either regular or covid infected lungs in the picture
img = Image.open(regular)#regular or covid lungs for testing
bw_img = img.convert('L')
bw_img

r = 0 #calculates quantity of redness in the image
g = 0 #calculates quantity of greenness in the image
b = 0 #calculates quantity of blueness in the image

#rgb value is a good measure of colour percentage in an image 

#here i am using rgb values to determine how much whiteness and blackness is in the image of the lungs xray

#if it is more white then it means that lungs is dense which might be a sign of covid

#rgb values near 300 percent means towards white and near 0 percent means black

#300 percent means 300*255

black = 0
white = 0
for x in range(bw_img.width):
        for y in range(bw_img.height):
            #for the given pixel at w,h, lets check its value against the threshold
            if bw_img.getpixel((x,y))< 127: 
                #this means the colour is towards black side
                black = black + 1
            else:
                #this means the colour is towards white side
                white = white + 1
wp = 0.0
bp = 0.0
wp = (100*white) / (white + black) #whiteness percentage
bp = (100*black) / (white + black) #blackness percentage
print("Note: These results are not accurate\n")
print("White percentage: ", wp)
print("Black percentage: ", bp)
print()
if(wp>=0 and wp<=60):
  print("Low Chances Of Covid-19")
elif(wp>60 and wp<=80):
  print("Medium Chances Of Covid-19")
else:
  print("High Chances Of Covid-19")